### ISSUE TITLE
IonicのテンプレートPJ作成

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/civilization#17]
# ionic reactチュートリアル プロジェクトの作成
公式にしたがってプロジェクトの作成
https://ionicframework.com/jp/docs/react/quickstart

①`npm install -g @ionic/cli`でIonic CLIをインストールする。
②`ionic start`を実行し、プロジェクト名、テンプレート、ベースのフレームワークを選択する。

所感：ionic startで作成されるテンプレートプロジェクトを見る限り、普通のcreate-react-appで作成されるプロジェクトと構造は変わらないので、コードを書く分には特段学習コストを必要としないと思われる。
ただ、Ionicがアプリの作成をサポートするテンプレートコンポーネントを内包しているので、これを使用する場合は確認が必要。
**各コンポーネントのルートはIonタグ系を使用しない場合でもIonPageでラップする必要があるとのこと。(routingが正しく働くことを保証するらしい)**

# ネイティブアプリ部分の設定
①`ionic integrations enable capacitor`を実行
これを入れることでネイティブのAPIを呼び出すことができるらしい。
②以下のコマンドを順に実行
```
ionic build
ionic cap add ios
ionic cap add android
```
③以下のコマンドを実行
```
ionic cap open ios
ionic cap open android
```
(ネイティブIDEを使用してiOSおよびAndroidプロジェクトを開いてビルドし、実行する。)
capacitorを使用して使えるネイティブのapiは以下のドキュメントを参照
https://capacitor.ionicframework.com/jp/docs/apis

# android エミュレータの動かし方
準備: Android Studioをinstallして、ネイティブアプリの設定の`ionic cap open android`までを実行する。
↓こちらの手順に従う。
https://developer.android.com/studio/run/emulator?hl=ja

# Ionic elements tagを使用する理由
普通にHTMLを書いていくのではなく、ion elements tagを使用する理由は、各プラットフォームで最適に動作するように設計されているためらしい。ion elements tagを使用すると300ms問題という遅延が生じなくなるとのこと。
https://stackoverflow.com/questions/52534148/why-use-ionic-element-tags-components-vs-standard-html

# 実装方針
ionicはネイティブでのパフォーマンスを損なわずにアプリを構築するという思想で設計されている。
そのためionicの恩恵を享受するには、ionicが提供するUIコンポーネントをなるべく使うようにして、実装していくようにする。
https://ionicframework.com/blog/where-does-ionic-react-fit-in-the-react-ecosystem/

# styled-componentsが使えるか
使えるっぽい
https://forum.ionicframework.com/t/using-styled-components/162223

**Comment by yamad07** [comment]
めちゃ良い調査！！

**Comment by harutaka814** [comment]
稼働 7h
