### ISSUE TITLE
負荷試験ツールのデプロイと試験運用 

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/civilization#25]
## 概要
- [こちら](https://github.com/ispec-inc/load-testing-sample)の林さんが作ってくれたECSのモジュールをもとに、負荷試験のクラスタをAWS上に構築する。
- 構築した上で、PlacyのステージングのレコメンドのAPIを叩いて、1秒間にどれくらいのリクエストに耐えられるかを調査する。

## 工数
**合計**
8

**コーディング**
4

**ロジック**
0

**キャッチアップ**
4

**Comment by tanimutomo** [comment]
![](https://gyazo.com/861a49b1eecba79bd36b1f5ffb7199b6)

![](https://gyazo.com/81f3cf4fc41eb9c73012f595d1c2517a)

![](https://gyazo.com/fe58170b0e7eb2c9bcd3755e7a492f47)
