### ISSUE TITLE
HanamiでgRPCのコントローラを書く

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/civilization#5]
Rubyの[Hanami](https://hanamirb.org/)というフレームワークで、[gRPC](https://grpc.io/)を使ったコントローラを書く。
Interactor、EntitiyのレイヤーにはgRPCのロジックが入らないように実装する。
ユーザーの情報を取得できるGetの処理と、ユーザーを作成できるCreateの処理を作ってほしいです。

工数
10
code: 4
logic: 2
thirdparty: 4

**Comment by Jonconan** [comment]
遅くなりまして申し訳ありません💦
https://github.com/ispec-inc/hanami-grcp-sample/pull/3#issuecomment-615137983

あともう一歩のところまで行けました、お手隙の際にご確認ください🙇‍♂️
