### ISSUE TITLE
Locustのボイラープレートを作成

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/civilization#7]
やること
- ispec-incのレポジトリの中に負荷試験用のLocustをすぐに立てられるDockerfileを作成する。
- それを使ってECS等にデプロイをすることで、シンプルなヘルスチェックのみの負荷試験のシナリオを実行することができる
工数
- 8

**Comment by snowman-mh** [comment]
# 実際に作るもの

- docker-composeを用いてローカルで負荷を受けるAPIサーバを立てられるサンプル
- docker-composeを用いてLocustのクラスタを立てて上記APIサーバに負荷をかけられるサンプル
- LocustクラスタをECS上に構築できるTerraform module
