### ISSUE TITLE
container definitionを外から設定できるようなECSのServiceを作成するモジュールの実装

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/civilization#8]
## やること
AWSECS上にサーバーの環境を構築するときに使える便利モジュール群
1. ECS Service
ECSのClusterとECRの情報等を渡すと，そのCluster上にECRのイメージが動くサービスを展開する．ALBの情報を渡さずにDaemonSet的に動くServiceを作ったりすることもできる.
2. ALB
ECS ServiceをALBでロードバランシングさせたいときに，使うモジュールで，AutoScale周りの設定が抽象化されている．
3. Scheduled Task
ECSのCluster上で定期的にバッチ処理をしたいときに用いるタスク
4. IAM Role module
ECS Serviceのモジュールの中で必要な権限を，このモジュールに渡すと，その権限を持つIAM Roleを作ってくれる．

## 工数
code: 8
logic: 2
thirdparty: 2

**Comment by snowman-mh** [comment]
https://ispec.slack.com/archives/CTS9D0HDW/p1591197221003800?thread_ts=1591084537.002400&cid=CTS9D0HDW
一応Slackでの議論のリンクをメモ

**Comment by snowman-mh** [comment]
https://github.com/ispec-inc/terraform-modules
一旦ここにモジュール群を作っていく方針にします。
何かもっと他に置きたいところがあれば全然移動できるので言ってください 🙏

**Comment by snowman-mh** [comment]
```
.
├── README.md
├── examples
│   └── ecs_service_with_alb
│       ├── main.tf
│       └── variables.tf
└── modules
    ├── alb
    │   ├── main.tf
    │   └── variables.tf
    ├── ecs_service
    │   ├── main.tf
    │   └── varibles.tf
    └── iam
        ├── main.tf
        └── variables.tf

6 directories, 9 files
```
こんな感じのディレクトリ構成でいきます。

**Comment by snowman-mh** [comment]
ECS Serviceのモジュールのところに、DaemonSetとして動くものにも対応する、という旨が書いてありますが、DaemonSetとして動くECS ServiceにはFargateは対応していないことを忘れていました。
DaemonSetに対応するとしたら、別途EC2 backendのECS Cluster上でDaemonSetとして動くECS Serviceのモジュールを実装する必要があるため、今回のIssueのスコープ外とさせていただきます 🙇
